# Turn ZMK Studio back on
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Boost Bluetooth signal to maximum
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# (Optional) Force stable long-range Bluetooth mode
CONFIG_BT_CTLR_PHY_2M=n
